### ISSUE TITLE
MemoryStoreService Outdated

### ISSUE THREAD

**Issue by pakamijo** [roblox-ts/services#22]
Memory Store service's Sorted Maps are missing `sortKey: unknown` parameter on `SetAsync` method

`MemoryStoreHashMap` type completely missing

**Comment by Dionysusnu** [comment]
I can't reproduce this. The playground shows the referenced types in intellisense, and compiles fine when using them. Maybe check that you're on the latest version of `@rbxts/types`? To update, run `npm i -D @rbxts/types@latest`.
